services:
  db:
    image: ankane/pgvector
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prosecutor_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:6333/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  drizzle-studio:
    image: ghcr.io/drizzle-team/drizzle-studio:latest
    ports:
      - 8899:8899
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/prosecutor_db"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
  qdrant_data:
