import type { RequestHandler } from '@sveltejs/kit';
import { json } from '@sveltejs/kit';

// AI citation suggestions endpoint
export const POST: RequestHandler = async ({ request }) => {
  try {
    const { currentText, selectedText, caseId, reportId } = await request.json();
    
    // Analyze text to identify citation opportunities
    const textToAnalyze = selectedText || currentText;
    const keywords = extractLegalKeywords(textToAnalyze);
    
    // Build AI prompt for citation suggestions
    const prompt = `Analyze this prosecutor's report text and suggest relevant legal citations:

Text: "${textToAnalyze}"

Legal keywords identified: ${keywords.join(', ')}

Suggest specific citations that would strengthen this argument, including:
1. Relevant case law
2. Applicable statutes 
3. Legal precedents
4. Constitutional provisions if applicable

Format each suggestion with label, content, and relevance score.`;

    // Call Legal-BERT for citation analysis
    const aiResponse = await fetch('http://localhost:5000/api/legal-bert/citations', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        text: textToAnalyze,
        keywords,
        jurisdiction: 'federal', // Could be dynamic based on case
        document_type: 'prosecutor_report'
      })
    });

    let suggestions: any[] = [];
    
    if (aiResponse.ok) {
      const aiResult = await aiResponse.json();
      suggestions = aiResult.citations || [];
    }
    
    // Fallback: Generate suggestions based on keyword analysis
    if (suggestions.length === 0) {
      suggestions = generateFallbackCitations(keywords, textToAnalyze);
    }

    // Convert to CitationPoint format
    const citationSuggestions = suggestions.map((suggestion, index) => ({
      id: crypto.randomUUID(),
      label: suggestion.label || `[${index + 1}]`,
      content: suggestion.content || suggestion.text || '',
      sourceType: suggestion.type || 'case_law' as const,
      sourceId: suggestion.sourceId,
      url: suggestion.url,
      page: suggestion.page,
      embedding: [], // Would be generated by embedding service
      tags: suggestion.tags || keywords,
      caseId,
      reportId,
      createdAt: new Date().toISOString(),
      synced: false
    }));

    return json(citationSuggestions);

  } catch (error) {
    console.error('Citation suggestion failed:', error);
    return json(
      { 
        error: 'Failed to generate citation suggestions',
        message: error instanceof Error ? error.message : 'Unknown error'
      }, 
      { status: 500 }
    );
  }
};

// Helper function to extract legal keywords
function extractLegalKeywords(text: string): string[] {
  const legalTerms = [
    'defendant', 'plaintiff', 'evidence', 'testimony', 'witness',
    'statute', 'constitutional', 'precedent', 'jurisdiction', 'liability',
    'negligence', 'intent', 'criminal', 'civil', 'contract', 'tort',
    'damages', 'injunction', 'motion', 'appeal', 'verdict', 'judgment',
    'due process', 'equal protection', 'probable cause', 'reasonable doubt',
    'search and seizure', 'miranda', 'confession', 'hearsay', 'objection'
  ];
  
  const words = text.toLowerCase().split(/\W+/);
  const foundTerms = legalTerms.filter(term => 
    words.some(word => word.includes(term) || term.includes(word))
  );
  
  return [...new Set(foundTerms)]; // Remove duplicates
}

// Helper function to generate fallback citations
function generateFallbackCitations(keywords: string[], text: string): any[] {
  const suggestions = [];
  
  if (keywords.includes('miranda') || keywords.includes('confession')) {
    suggestions.push({
      label: '[Miranda]',
      content: 'Miranda v. Arizona, 384 U.S. 436 (1966) - Custodial interrogation requires warnings',
      type: 'case_law',
      tags: ['miranda', 'interrogation', 'confession']
    });
  }
  
  if (keywords.includes('search') || keywords.includes('seizure')) {
    suggestions.push({
      label: '[Fourth Amendment]',
      content: 'U.S. Const. amend. IV - Protection against unreasonable searches and seizures',
      type: 'constitutional',
      tags: ['fourth amendment', 'search', 'seizure']
    });
  }
  
  if (keywords.includes('due process')) {
    suggestions.push({
      label: '[Due Process]',
      content: 'U.S. Const. amend. XIV - No state shall deny equal protection or due process',
      type: 'constitutional',
      tags: ['due process', 'constitutional']
    });
  }
  
  if (keywords.includes('evidence')) {
    suggestions.push({
      label: '[Evidence Rule]',
      content: 'Fed. R. Evid. 401 - Test for relevant evidence',
      type: 'statute',
      tags: ['evidence', 'relevance', 'federal rules']
    });
  }
  
  if (keywords.includes('reasonable doubt')) {
    suggestions.push({
      label: '[Burden of Proof]',
      content: 'In re Winship, 397 U.S. 358 (1970) - Beyond reasonable doubt standard in criminal cases',
      type: 'case_law',
      tags: ['burden of proof', 'reasonable doubt', 'criminal']
    });
  }
  
  return suggestions.slice(0, 5); // Limit to 5 suggestions
}
