-- Insert sample data for testing CRUD features and dashboard

-- Sample Cases
INSERT INTO cases (
    id,
    case_number,
    title,
    description,
    status,
    priority,
    filing_date,
    court_room,
    jurisdiction,
    created_by,
    lead_prosecutor,
    estimated_trial_date
) VALUES 
(
    gen_random_uuid(),
    'CASE-2025-001',
    'State vs. Smith - Financial Fraud',
    'Investigation into alleged financial fraud involving multiple bank accounts and unauthorized transactions totaling $75,000',
    'investigation',
    'high',
    '2025-01-15',
    'Courtroom 5A',
    'State Court',
    (SELECT id FROM users WHERE email = 'example@example.com'),
    (SELECT id FROM users WHERE email = 'example@example.com'),
    '2025-08-15'
),
(
    gen_random_uuid(),
    'CASE-2025-002',
    'People vs. Johnson - Drug Trafficking',
    'Major drug trafficking case involving interstate commerce and distribution of controlled substances',
    'active',
    'critical',
    '2025-02-01',
    'Courtroom 3B',
    'Federal Court',
    (SELECT id FROM users WHERE email = 'example@example.com'),
    (SELECT id FROM users WHERE email = 'example@example.com'),
    '2025-09-20'
),
(
    gen_random_uuid(),
    'CASE-2025-003',
    'State vs. Williams - Cybercrime',
    'Cybercrime investigation involving identity theft and online fraud schemes affecting elderly victims',
    'pending',
    'medium',
    '2025-02-15',
    'Courtroom 2A',
    'State Court',
    (SELECT id FROM users WHERE email = 'example@example.com'),
    (SELECT id FROM users WHERE email = 'example@example.com'),
    '2025-07-10'
);

-- Sample Criminals
INSERT INTO criminals (
    id,
    first_name,
    last_name,
    date_of_birth,
    address,
    phone_number,
    email,
    emergency_contact,
    occupation,
    employers,
    aliases,
    identifying_marks,
    criminal_history,
    created_by
) VALUES 
(
    gen_random_uuid(),
    'Robert',
    'Smith',
    '1985-03-15',
    '123 Main Street, Anytown, ST 12345',
    '555-0123',
    'robert.smith@email.com',
    'Jane Smith - Wife - 555-0124',
    'Accountant',
    '[{"name": "ABC Accounting Firm", "position": "Senior Accountant", "duration": "2018-2024"}]'::jsonb,
    '["Bob Smith", "R. Smith", "Bobby"]'::jsonb,
    'Scar on left hand from childhood accident',
    'No prior convictions',
    (SELECT id FROM users WHERE email = 'example@example.com')
),
(
    gen_random_uuid(),
    'Michael',
    'Johnson',
    '1978-11-22',
    '456 Oak Avenue, Metro City, ST 67890',
    '555-0456',
    'mj.johnson@email.com',
    'Lisa Johnson - Sister - 555-0789',
    'Truck Driver',
    '[{"name": "Metro Logistics", "position": "Long-haul Driver", "duration": "2015-2024"}]'::jsonb,
    '["Mike Johnson", "Big Mike", "MJ"]'::jsonb,
    'Tattoo of eagle on right shoulder',
    'Previous arrests: DUI (2019), Drug possession (2021)',
    (SELECT id FROM users WHERE email = 'example@example.com')
),
(
    gen_random_uuid(),
    'Sarah',
    'Williams',
    '1992-07-08',
    '789 Pine Street, Techville, ST 11111',
    '555-0789',
    'sarah.williams@techmail.com',
    'David Williams - Brother - 555-0321',
    'Software Developer',
    '[{"name": "TechCorp Solutions", "position": "Junior Developer", "duration": "2020-2023"}]'::jsonb,
    '["Sara Williams", "S. Williams", "Techie Sara"]'::jsonb,
    'Small birthmark on neck',
    'No criminal history',
    (SELECT id FROM users WHERE email = 'example@example.com')
);

-- Sample Evidence (linking to cases)
INSERT INTO evidence (
    id,
    case_id,
    file_name,
    file_path,
    file_type,
    file_size,
    upload_date,
    description,
    tags,
    summary,
    uploaded_by
) VALUES 
(
    gen_random_uuid(),
    (SELECT id FROM cases WHERE case_number = 'CASE-2025-001'),
    'bank_statements_jan_2025.pdf',
    '/uploads/evidence/bank_statements_jan_2025.pdf',
    'application/pdf',
    2048576,
    NOW(),
    'Bank statements showing suspicious transactions and unauthorized transfers',
    '["financial", "fraud", "bank-records", "january-2025"]'::jsonb,
    'Contains evidence of 15 unauthorized transfers totaling $45,000 between January 1-31, 2025',
    (SELECT id FROM users WHERE email = 'example@example.com')
),
(
    gen_random_uuid(),
    (SELECT id FROM cases WHERE case_number = 'CASE-2025-001'),
    'accounting_software_logs.xlsx',
    '/uploads/evidence/accounting_software_logs.xlsx',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    1536000,
    NOW(),
    'Detailed logs from accounting software showing manual entry modifications',
    '["financial", "fraud", "software-logs", "accounting"]'::jsonb,
    'Log entries show 23 manual modifications to transaction records, all made outside business hours',
    (SELECT id FROM users WHERE email = 'example@example.com')
),
(
    gen_random_uuid(),
    (SELECT id FROM cases WHERE case_number = 'CASE-2025-002'),
    'drug_seizure_photos.zip',
    '/uploads/evidence/drug_seizure_photos.zip',
    'application/zip',
    15728640,
    NOW(),
    'Photographs from drug seizure operation including packaging and scale photos',
    '["drugs", "trafficking", "seizure", "photos"]'::jsonb,
    'Contains 47 high-resolution photos documenting seizure of 2.5kg cocaine and packaging materials',
    (SELECT id FROM users WHERE email = 'example@example.com')
),
(
    gen_random_uuid(),
    (SELECT id FROM cases WHERE case_number = 'CASE-2025-003'),
    'victim_communications.eml',
    '/uploads/evidence/victim_communications.eml',
    'message/rfc822',
    256000,
    NOW(),
    'Email communications between perpetrator and elderly victims',
    '["cybercrime", "identity-theft", "emails", "victim-communications"]'::jsonb,
    'Email chain showing phishing attempts and personal information harvesting targeting 12 elderly victims',
    (SELECT id FROM users WHERE email = 'example@example.com')
);

-- Sample Crimes (linking criminals to cases)
INSERT INTO crimes (
    id,
    case_id,
    criminal_id,
    crime_type,
    description,
    date_committed,
    location,
    charges,
    evidence_collected,
    witness_statements,
    police_report_number,
    severity_level,
    status,
    plea,
    sentence,
    created_by
) VALUES 
(
    gen_random_uuid(),
    (SELECT id FROM cases WHERE case_number = 'CASE-2025-001'),
    (SELECT id FROM criminals WHERE first_name = 'Robert' AND last_name = 'Smith'),
    'Financial Fraud',
    'Systematic embezzlement from employer accounts using position of trust',
    '2024-12-15',
    'ABC Accounting Firm, 100 Business Plaza, Anytown, ST',
    '["Grand Theft", "Embezzlement", "Fraud", "Identity Theft"]'::jsonb,
    '["Bank statements", "Accounting software logs", "Witness testimonies"]'::jsonb,
    '["Employer statement", "Victim impact statements", "Coworker testimonies"]'::jsonb,
    'PR-2025-001-FIN',
    'felony',
    'investigation',
    null,
    null,
    (SELECT id FROM users WHERE email = 'example@example.com')
),
(
    gen_random_uuid(),
    (SELECT id FROM cases WHERE case_number = 'CASE-2025-002'),
    (SELECT id FROM criminals WHERE first_name = 'Michael' AND last_name = 'Johnson'),
    'Drug Trafficking',
    'Interstate drug trafficking operation using commercial trucking routes',
    '2024-11-30',
    'I-75 Corridor, Multiple States',
    '["Drug Trafficking", "Interstate Commerce Violation", "Conspiracy"]'::jsonb,
    '["Drug seizure", "Vehicle search", "Communication intercepts"]'::jsonb,
    '["Informant statements", "Surveillance footage", "Co-conspirator testimony"]'::jsonb,
    'PR-2025-002-DRG',
    'felony',
    'active',
    null,
    null,
    (SELECT id FROM users WHERE email = 'example@example.com')
),
(
    gen_random_uuid(),
    (SELECT id FROM cases WHERE case_number = 'CASE-2025-003'),
    (SELECT id FROM criminals WHERE first_name = 'Sarah' AND last_name = 'Williams'),
    'Cybercrime',
    'Identity theft and online fraud targeting elderly victims through phishing schemes',
    '2024-10-01',
    'Online/Multiple victim locations',
    '["Identity Theft", "Wire Fraud", "Elder Abuse", "Computer Fraud"]'::jsonb,
    '["Email communications", "Financial records", "IP traces", "Computer forensics"]'::jsonb,
    '["Victim statements", "Family member testimony", "Bank representative testimony"]'::jsonb,
    'PR-2025-003-CYB',
    'felony',
    'pending',
    null,
    null,
    (SELECT id FROM users WHERE email = 'example@example.com')
);
