[package]
name = "prosecutor-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web framework
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "fs"] }
hyper = "1.0"

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

# Vector Database & AI
qdrant-client = "1.7"
candle-core = "0.4"
candle-nn = "0.4" 
candle-transformers = "0.4"
tokenizers = "0.15"
hf-hub = "0.3"

# File Processing & OCR
pdf-extract = "0.7"
tesseract = "0.14"
image = "0.24"
ffmpeg-next = "6.0"

# Text Processing & Embeddings
fastembed = "3.0"
text-splitter = "0.4"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Authentication
jsonwebtoken = "9.0"
bcrypt = "0.15"
argon2 = "0.5"

# Environment and configuration
dotenv = "0.15"
anyhow = "1.0"
thiserror = "1.0"

# File handling and uploads
multer = "3.0"
mime = "0.3"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Utilities
rand = "0.8"

# Development dependencies
[dev-dependencies]
reqwest = { version = "0.12", features = ["json", "multipart"] }
tempfile = "3.8"

# Tauri dependencies for desktop app
[features]
default = []
tauri = ["tauri-build"]

[build-dependencies]
tauri-build = { version = "1.5", optional = true }
